### ISSUE TITLE
Can't get Accounts

### ISSUE THREAD

**Issue by jonpinedo** [Invertee/GDAX-Powershell#9]
When invoking "Get-CoinbaseProAccounts" I get this:

`Invoke-CoinbaseProRequest : Bad Request. Invalid request format
En C:\Program Files\WindowsPowerShell\Modules\CoinbasePro-Powershell\0.7.6\Functions\Private\Get-CoinbaseProAccounts.ps1: 
19 Carácter: 17
+     $response = Invoke-CoinbaseProRequest $api
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CoinbaseProRequest`

Any clues?

**Comment by neopsyon** [comment]
I took this module and started rewriting it, anyway seems like there is an issue with the timestamp header and I can't figure it out still why, since it's being casted as a string.

**Comment by alain-bora** [comment]
The issue is due to the formatting of the round function (line 10 of the file Functions/Invoke-CoinbaseRequest.ps1). Depending on the locale it will generate the timestamp with a comma or a dot.
A quick fix is:
From:
`$Timestamp = ([math]::Round($Timestamp, 3)).ToString()`
to:
`$Timestamp = ([math]::Round($Timestamp, 0)).ToString()`

**Comment by alain-bora** [comment]
> I took this module and started rewriting it, anyway seems like there is an issue with the timestamp header and I can't figure it out still why, since it's being casted as a string.

The issue is due to the formatting of the round function (line 10 of the file Functions/Invoke-CoinbaseRequest.ps1). Depending on the locale it will generate the timestamp with a comma or a dot.
A quick fix is:
From:
`$Timestamp = ([math]::Round($Timestamp, 3)).ToString()`
to:
`$Timestamp = ([math]::Round($Timestamp, 0)).ToString()`

**Comment by ChristianTroll** [comment]
Have the same issue. Answer is "Unauthorized. Invalid API key". Thats wrong, the values i provide are correct. I also tried the fix with the $timestamp. Doesn´t help.
Any more ideas? Thanks in advance

**Comment by stephenc01** [comment]
What version of PS?

**Comment by jonpinedo** [comment]
I'm using this version:

Version      
-------      
5.1.19041.610

**Comment by stephenc01** [comment]
Im using 7.1 core on a Mac. Ill test later on a PC.

**Comment by stephenc01** [comment]
Try changing timestamp to the following. 

$Timestamp = Get-Date -UFormat %s

**Comment by Invertee** [comment]
Rounded timestamps and uploaded new version to Powershell Gallery.
